version: '3.7'
networks:
  minha_rede:
    driver: bridge
services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - minha_rede
    depends_on:
      - mongo
  mongo:
    build: ./mongo_rs
    networks:
      - minha_rede
    environment:
      MONGO_INITDB_ROOT_USERNAME: usuario
      MONGO_INITDB_ROOT_PASSWORD: senhaaaaaaa
      MONGO_INITDB_DATABASE: aulas_mongo
      MONGO_REPLICA_HOST: mongo
      MONGO_REPLICA_PORT: 27017
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    name: mongodb_data